all:
  hosts:
    n1:
      ansible_host: 10.5.0.100
      ansible_connection: local
      network:
        ceph_public: true
        ceph_cluster: true
        ceph_mgmt: true
        mongo_mongos: true
        mongo_shard: true
        mongo_config: true
      ufw:
        reset: true
        ceph: true
        mongo_mongos: false
        mongo_shard: false
        mongo_config: false
        vault_server: true
    tableTopNode1:
      ansible_host: 10.5.0.101
      network:
        ceph_public: true
        ceph_cluster: true
        ceph_mgmt: true
        mongo_mongos: true
        mongo_shard: true
        mongo_config: true
      ufw:
        reset: true
        ceph: true
        mongo_mongos: true
        mongo_shard: true
        mongo_config: true
        vault_server: false
    tableTopNode2:
      ansible_host: 10.5.0.102
      network:
        ceph_public: true
        ceph_cluster: true
        ceph_mgmt: true
        mongo_mongos: true
        mongo_shard: true
        mongo_config: true
      ufw:
        reset: true
        ceph: true
        mongo_mongos: true
        mongo_shard: true
        mongo_config: true
        vault_server: false
    tableTopNode3:
      ansible_host: 10.5.0.103
      network:
        ceph_public: true
        ceph_cluster: true
        ceph_mgmt: true
        mongo_mongos: true
        mongo_shard: true
        mongo_config: true
      ufw:
        reset: true
        ceph: true
        mongo_mongos: true
        mongo_shard: true
        mongo_config: true
        vault_server: false

  children:
    physical:
      hosts:
        n1:

    vms:
      hosts:
        tableTopNode1:
        tableTopNode2:
        tableTopNode3:

    remove_physical:
      hosts:
        n1:

    remove_vms:
      hosts:
        tableTopNode1:
        tableTopNode2:
        tableTopNode3:

    ufw:
      hosts:
        n1:
        # tableTopNode1:
        # tableTopNode2:
        # tableTopNode3:
