- name: Init physical machine networking
  hosts: physical
  become: true
  vars_files:
    - ../vars/share.yaml
    - ../vars/physical.yaml
  roles:
    - role: ufw
    - role: init-networking-physical
